# Generated by Django 5.0.6 on 2024-06-14 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rpa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log_rpa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration', models.DurationField(blank=True, null=True)),
                ('rpa_log_status', models.CharField(choices=[('success', 'Success'), ('fault', 'Fault')], max_length=50)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('rpa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rpa_id', to='Rpa.rpa')),
            ],
        ),
    ]
