# Generated by Django 5.0.6 on 2024-06-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rpa', '0002_log_rpa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Error_rpa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='Log_rpa',
            new_name='Log_rpa_model',
        ),
        migrations.AddField(
            model_name='rpa',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
