# Generated by Django 5.0.6 on 2024-06-17 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rpa', '0003_error_rpa_rename_log_rpa_log_rpa_model_rpa_duration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Error_rpa',
            new_name='Error_rpa_model',
        ),
        migrations.RenameModel(
            old_name='Rpa',
            new_name='Rpa_model',
        ),
    ]
