# Generated by Django 5.0.6 on 2024-06-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rpa', '0004_rename_error_rpa_error_rpa_model_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Error_rpa_model',
        ),
        migrations.AddField(
            model_name='rpa_model',
            name='error_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
