# Generated by Django 5.0.6 on 2024-06-17 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rpa', '0005_delete_error_rpa_model_rpa_model_error_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Error_rpa_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_mensage', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('log_error', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='Rpa.log_rpa_model')),
            ],
        ),
    ]
