# Generated by Django 5.0.6 on 2024-06-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rpa', '0007_rpa_model_created_at_rpa_model_update_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpa_model',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rpa_model',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
