# Generated by Django 5.0.6 on 2024-06-17 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rpa', '0008_alter_rpa_model_created_at_alter_rpa_model_update_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='error_rpa_model',
            old_name='log_error',
            new_name='log_id',
        ),
    ]
