# Generated by Django 5.0.6 on 2024-06-17 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rpa', '0009_rename_log_error_error_rpa_model_log_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Error_rpa_model',
        ),
    ]
