# Generated by Django 5.0.6 on 2024-06-17 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rpa', '0011_log_rpa_error_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log_rpa_error_model',
            old_name='log_id',
            new_name='rpa_id',
        ),
    ]
