# Generated by Django 5.0.6 on 2024-06-18 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rpa', '0012_rename_log_id_log_rpa_error_model_rpa_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log_rpa_model',
            name='duration',
            field=models.DurationField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rpa_model',
            name='duration',
            field=models.DurationField(blank=True, default=datetime.timedelta, null=True),
        ),
    ]
