# Generated by Django 5.0.6 on 2024-06-18 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rpa', '0013_alter_log_rpa_model_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log_rpa_model',
            name='duration',
            field=models.DurationField(blank=True, default=datetime.timedelta, null=True),
        ),
    ]
