# Generated by Django 5.0.6 on 2024-06-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rpa', '0014_alter_log_rpa_model_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log_rpa_model',
            name='duration',
            field=models.DurationField(blank=True, default=0, null=True),
        ),
    ]
