# Generated by Django 5.0.6 on 2024-06-18 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rpa', '0015_alter_log_rpa_model_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpa_model',
            name='duration',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), null=True),
        ),
    ]
