# Generated by Django 5.0.6 on 2024-06-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rpa', '0016_alter_rpa_model_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpa_model',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
