# Generated by Django 5.0.7 on 2024-07-26 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpa_log_successes', '0002_rename_rpalogsucess_rpalogsuccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpalogsuccess',
            name='end_time',
            field=models.DateTimeField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rpalogsuccess',
            name='start_time',
            field=models.DateTimeField(blank=True, default=0, null=True),
        ),
    ]
