# Generated by Django 5.0.7 on 2024-07-26 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rpa_log_errors', '0001_initial'),
        ('rpas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RpaLogSucess',
            new_name='RpaLogError',
        ),
    ]
