# Generated by Django 5.0.7 on 2024-07-30 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rpa_log_errors', '0002_rename_rpalogsucess_rpalogerror'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rpalogerror',
            old_name='rpa_id',
            new_name='rpa',
        ),
    ]
