# Generated by Django 5.0.7 on 2024-07-26 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rpas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RpaLogSucess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration', models.DurationField(blank=True, default=0, null=True)),
                ('rpa_log_status', models.CharField(choices=[('success', 'Success')], default='success', max_length=50)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('rpa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_success_id_rpa', to='rpas.rpa')),
            ],
        ),
    ]
