# Generated by Django 5.0.7 on 2024-07-26 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rpa_log_successes', '0001_initial'),
        ('rpas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RpaLogSucess',
            new_name='RpaLogSuccess',
        ),
    ]
