# Generated by Django 5.0.7 on 2024-07-30 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rpa_log_successes', '0003_alter_rpalogsuccess_end_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rpalogsuccess',
            old_name='rpa_id',
            new_name='rpa',
        ),
    ]
